version: '3'
services:
  assigment:
    build: .
    ports:
      - "4000:4000"
    networks:
      - my-network
    environment:
      DB_URI: ${DB_URI}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      
  redis: 
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - my-network

networks:
  my-network:
    driver: bridge